#!/bin/bash
# /etc/init.d/magicwand
### BEGIN INIT INFO
# Provides:          harrypotter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

cd /home/pi/MagicWand
DATE=`date +/home/pi/MagicWand/log/HP%Y-%m-%d_%H%M.log`
sudo -u pi touch ${DATE}
./MWService.sh>${DATE}
